package com.kolarbear.wanandroid.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.kolarbear.wanandroid.bean.home.HomeBanner;
import com.kolarbear.wanandroid.bean.home.Articles;
import com.kolarbear.wanandroid.bean.knowledge.KnowledgeBean;
import com.kolarbear.wanandroid.bean.hot.HotBean;
import com.kolarbear.wanandroid.bean.hot.WebsiteBean;

import com.kolarbear.wanandroid.greendao.HomeBannerDao;
import com.kolarbear.wanandroid.greendao.ArticlesDao;
import com.kolarbear.wanandroid.greendao.KnowledgeBeanDao;
import com.kolarbear.wanandroid.greendao.HotBeanDao;
import com.kolarbear.wanandroid.greendao.WebsiteBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig homeBannerDaoConfig;
    private final DaoConfig articlesDaoConfig;
    private final DaoConfig knowledgeBeanDaoConfig;
    private final DaoConfig hotBeanDaoConfig;
    private final DaoConfig websiteBeanDaoConfig;

    private final HomeBannerDao homeBannerDao;
    private final ArticlesDao articlesDao;
    private final KnowledgeBeanDao knowledgeBeanDao;
    private final HotBeanDao hotBeanDao;
    private final WebsiteBeanDao websiteBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        homeBannerDaoConfig = daoConfigMap.get(HomeBannerDao.class).clone();
        homeBannerDaoConfig.initIdentityScope(type);

        articlesDaoConfig = daoConfigMap.get(ArticlesDao.class).clone();
        articlesDaoConfig.initIdentityScope(type);

        knowledgeBeanDaoConfig = daoConfigMap.get(KnowledgeBeanDao.class).clone();
        knowledgeBeanDaoConfig.initIdentityScope(type);

        hotBeanDaoConfig = daoConfigMap.get(HotBeanDao.class).clone();
        hotBeanDaoConfig.initIdentityScope(type);

        websiteBeanDaoConfig = daoConfigMap.get(WebsiteBeanDao.class).clone();
        websiteBeanDaoConfig.initIdentityScope(type);

        homeBannerDao = new HomeBannerDao(homeBannerDaoConfig, this);
        articlesDao = new ArticlesDao(articlesDaoConfig, this);
        knowledgeBeanDao = new KnowledgeBeanDao(knowledgeBeanDaoConfig, this);
        hotBeanDao = new HotBeanDao(hotBeanDaoConfig, this);
        websiteBeanDao = new WebsiteBeanDao(websiteBeanDaoConfig, this);

        registerDao(HomeBanner.class, homeBannerDao);
        registerDao(Articles.class, articlesDao);
        registerDao(KnowledgeBean.class, knowledgeBeanDao);
        registerDao(HotBean.class, hotBeanDao);
        registerDao(WebsiteBean.class, websiteBeanDao);
    }
    
    public void clear() {
        homeBannerDaoConfig.clearIdentityScope();
        articlesDaoConfig.clearIdentityScope();
        knowledgeBeanDaoConfig.clearIdentityScope();
        hotBeanDaoConfig.clearIdentityScope();
        websiteBeanDaoConfig.clearIdentityScope();
    }

    public HomeBannerDao getHomeBannerDao() {
        return homeBannerDao;
    }

    public ArticlesDao getArticlesDao() {
        return articlesDao;
    }

    public KnowledgeBeanDao getKnowledgeBeanDao() {
        return knowledgeBeanDao;
    }

    public HotBeanDao getHotBeanDao() {
        return hotBeanDao;
    }

    public WebsiteBeanDao getWebsiteBeanDao() {
        return websiteBeanDao;
    }

}
