package com.kolarbear.wanandroid.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.kolarbear.wanandroid.bean.home.HomeBanner;
import com.kolarbear.wanandroid.bean.home.Articles;

import com.kolarbear.wanandroid.greendao.HomeBannerDao;
import com.kolarbear.wanandroid.greendao.ArticlesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig homeBannerDaoConfig;
    private final DaoConfig articlesDaoConfig;

    private final HomeBannerDao homeBannerDao;
    private final ArticlesDao articlesDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        homeBannerDaoConfig = daoConfigMap.get(HomeBannerDao.class).clone();
        homeBannerDaoConfig.initIdentityScope(type);

        articlesDaoConfig = daoConfigMap.get(ArticlesDao.class).clone();
        articlesDaoConfig.initIdentityScope(type);

        homeBannerDao = new HomeBannerDao(homeBannerDaoConfig, this);
        articlesDao = new ArticlesDao(articlesDaoConfig, this);

        registerDao(HomeBanner.class, homeBannerDao);
        registerDao(Articles.class, articlesDao);
    }
    
    public void clear() {
        homeBannerDaoConfig.clearIdentityScope();
        articlesDaoConfig.clearIdentityScope();
    }

    public HomeBannerDao getHomeBannerDao() {
        return homeBannerDao;
    }

    public ArticlesDao getArticlesDao() {
        return articlesDao;
    }

}
