package com.kolarbear.wanandroid.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.kolarbear.wanandroid.bean.hot.WebsiteBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WEBSITE_BEAN".
*/
public class WebsiteBeanDao extends AbstractDao<WebsiteBean, Long> {

    public static final String TABLENAME = "WEBSITE_BEAN";

    /**
     * Properties of entity WebsiteBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Index = new Property(0, Long.class, "index", true, "_id");
        public final static Property Icon = new Property(1, String.class, "icon", false, "ICON");
        public final static Property Id = new Property(2, int.class, "id", false, "ID");
        public final static Property Link = new Property(3, String.class, "link", false, "LINK");
        public final static Property Name = new Property(4, String.class, "name", false, "NAME");
        public final static Property Order = new Property(5, int.class, "order", false, "ORDER");
        public final static Property Visible = new Property(6, int.class, "visible", false, "VISIBLE");
    }


    public WebsiteBeanDao(DaoConfig config) {
        super(config);
    }
    
    public WebsiteBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WEBSITE_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: index
                "\"ICON\" TEXT," + // 1: icon
                "\"ID\" INTEGER NOT NULL ," + // 2: id
                "\"LINK\" TEXT," + // 3: link
                "\"NAME\" TEXT," + // 4: name
                "\"ORDER\" INTEGER NOT NULL ," + // 5: order
                "\"VISIBLE\" INTEGER NOT NULL );"); // 6: visible
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WEBSITE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, WebsiteBean entity) {
        stmt.clearBindings();
 
        Long index = entity.getIndex();
        if (index != null) {
            stmt.bindLong(1, index);
        }
 
        String icon = entity.getIcon();
        if (icon != null) {
            stmt.bindString(2, icon);
        }
        stmt.bindLong(3, entity.getId());
 
        String link = entity.getLink();
        if (link != null) {
            stmt.bindString(4, link);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
        stmt.bindLong(6, entity.getOrder());
        stmt.bindLong(7, entity.getVisible());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, WebsiteBean entity) {
        stmt.clearBindings();
 
        Long index = entity.getIndex();
        if (index != null) {
            stmt.bindLong(1, index);
        }
 
        String icon = entity.getIcon();
        if (icon != null) {
            stmt.bindString(2, icon);
        }
        stmt.bindLong(3, entity.getId());
 
        String link = entity.getLink();
        if (link != null) {
            stmt.bindString(4, link);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
        stmt.bindLong(6, entity.getOrder());
        stmt.bindLong(7, entity.getVisible());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public WebsiteBean readEntity(Cursor cursor, int offset) {
        WebsiteBean entity = new WebsiteBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // index
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // icon
            cursor.getInt(offset + 2), // id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // link
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // name
            cursor.getInt(offset + 5), // order
            cursor.getInt(offset + 6) // visible
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, WebsiteBean entity, int offset) {
        entity.setIndex(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIcon(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setId(cursor.getInt(offset + 2));
        entity.setLink(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setOrder(cursor.getInt(offset + 5));
        entity.setVisible(cursor.getInt(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(WebsiteBean entity, long rowId) {
        entity.setIndex(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(WebsiteBean entity) {
        if(entity != null) {
            return entity.getIndex();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(WebsiteBean entity) {
        return entity.getIndex() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
